name = "JSObjectLiteral"
uuid = "a7b85b94-2b9e-11e9-2e5f-79ec22955f58"
authors = ["David A. van Leeuwen <david.vanleeuwen@gmail.com>"]
version = "0.1.0"

[deps]
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
